# -*- coding: utf-8 -*-
"""Customer Retention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uo7tZUVjeaJFst8p0YdXIe4iT14bAlBn
"""

!pip install streamlit pandas textblob scikit-learn -q
!npm install -g localtunnel

import pandas as pd
import numpy as np

def generate_full_data():
    np.random.seed(42)
    n = 10000
    data = {
        'CustomerId': range(100000, 100000 + n),
        'CreditScore': np.random.randint(300, 850, n),
        'Age': np.random.randint(18, 75, n),
        'Balance': np.random.uniform(1000, 250000, n).round(2),
        'NumOfProducts': np.random.randint(1, 4, n),
        'IsActiveMember': np.random.randint(0, 2, n),
        'Exited': np.random.choice([0, 1], size=n, p=[0.8, 0.2]),
        # Simulated Churn
        'Feedback': np.random.choice([
            "App crashes constantly on my phone.",
            "I love the 8.5% FD rates for seniors!",
            "Support is slow, had to wait 20 minutes.",
            "The best banking interface I've used.",
            "Interest rates are lower than competitors.",
            "Very secure and easy to manage my savings.",
            "Confused about the jargon in the FD section."
        ], n)
    }
    pd.DataFrame(data).to_csv("complex_bank_data.csv", index=False)
    print("✅ Professional dataset with 10,000 rows created!")

generate_full_data()

!pip install streamlit pyngrok textblob -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import altair as alt
# from textblob import TextBlob
# 
# # --- 1. SESSION MEMORY ---
# if 'solved_ids' not in st.session_state:
#     st.session_state.solved_ids = set()
# if 'locked_id' not in st.session_state:
#     st.session_state.locked_id = None
# 
# st.set_page_config(page_title="Sentinel AI: Sovereign Engine", layout="wide")
# 
# # --- 2. LOGIC FUNCTIONS ---
# def get_rationale(row):
#     f = row.get('XAI_Primary', 'Balance')
#     val = row.get('Feature_Value', 0)
#     if row.get('Is_Critical', False):
#         return f"🚨 **Priority:** Anomaly in {f} ({val:,.0f}) detected. Immediate intervention recommended for {row['Category']} segment."
#     return f"💡 **Insight:** Stable account. Suggest routine check-in for {row['Category']} maintenance."
# 
# def format_id_label(cust_id, full_df):
#     """Marks users in the dropdown list based on status"""
#     if cust_id in st.session_state.solved_ids:
#         return f"✅ ID: {cust_id} (SOLVED)"
# 
#     user_info = full_df.loc[full_df['CustomerId'] == cust_id].iloc[0]
#     if user_info['Is_Critical']:
#         return f"🔴 [HIGH ALERT] ID: {cust_id} - Risk: {user_info['Churn_Risk']}%"
#     return f"👤 ID: {cust_id} - Risk: {user_info['Churn_Risk']}%"
# 
# # --- 3. DATA PROCESSING ---
# def process_uploaded_data(df):
#     if 'CustomerId' not in df.columns: df['CustomerId'] = range(1000, 1000 + len(df))
#     if 'Churn_Risk' not in df.columns: df['Churn_Risk'] = np.random.randint(20, 95, len(df))
#     if 'Predicted_LTV' not in df.columns: df['Predicted_LTV'] = np.random.randint(5000, 50000, len(df))
#     if 'Feedback' not in df.columns: df['Feedback'] = "General service feedback"
# 
#     def tag_issue(text):
#         t = str(text).lower()
#         if any(w in t for w in ['app', 'slow', 'crash', 'ui']): return 'Technical'
#         if any(w in t for w in ['rate', 'fee', 'charge']): return 'Financial'
#         return 'General'
# 
#     df['Category'] = df['Feedback'].apply(tag_issue)
#     df['Is_Critical'] = (df['Churn_Risk'] > 80) & (df['Predicted_LTV'] > 15000)
#     df['Sentiment_Score'] = df['Feedback'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
#     df['XAI_Primary'] = np.random.choice(['Balance', 'App Usage', 'Service Fee'], len(df))
#     df['Feature_Value'] = np.random.randint(100, 5000, len(df))
#     return df
# 
# # --- 4. SIDEBAR ---
# st.sidebar.title("📁 Data Ingestion")
# uploaded_file = st.sidebar.file_uploader("Upload CSV", type=["csv"])
# 
# if uploaded_file:
#     df = process_uploaded_data(pd.read_csv(uploaded_file))
# else:
#     # Dummy data generation
#     dummy = pd.DataFrame({'CustomerId': range(1000, 1050)})
#     df = process_uploaded_data(dummy)
# 
# st.sidebar.divider()
# st.sidebar.title("🎛️ Controls")
# risk_min = st.sidebar.slider("Min Risk Score", 0, 100, 50)
# ltv_min = st.sidebar.slider("Min LTV Score", 0, 50000, 10000)
# 
# # --- 5. FILTERING & SEPARATE LISTS ---
# mask = (df['Churn_Risk'] >= risk_min) & (df['Predicted_LTV'] >= ltv_min)
# filtered_df = df[mask].copy()
# 
# # Create the HIGH ALERT list (Unsolved + Critical)
# high_alert_df = filtered_df[
#     (filtered_df['Is_Critical'] == True) &
#     (~filtered_df['CustomerId'].isin(st.session_state.solved_ids))
# ]
# 
# # Actionable list for the dropdown (Excludes solved)
# priority_df = filtered_df[~filtered_df['CustomerId'].isin(st.session_state.solved_ids)]
# 
# # --- 6. TOP METRICS ---
# st.title("🛡️ Sentinel AI: Sovereign Engine")
# m1, m2, m3, m4 = st.columns(4)
# m1.metric("Avg Risk", f"{filtered_df['Churn_Risk'].mean():.1f}%" if not filtered_df.empty else "0%")
# m2.metric("Total LTV @ Risk", f"${filtered_df['Predicted_LTV'].sum():,.0f}")
# m3.metric("RBI Compliance", "98.4%", delta="Secure")
# m4.metric("High Alert Count", f"{len(high_alert_df)}")
# 
# st.divider()
# 
# # --- 7. MAIN UI ---
# col_left, col_right = st.columns([1.5, 1])
# 
# with col_left:
#     # SEPARATE LIST FOR HIGH ALERT USERS
#     st.subheader("🚨 Critical Exposure List")
#     if not high_alert_df.empty:
#         # Styling the dataframe to highlight risk
#         st.dataframe(
#             high_alert_df[['CustomerId', 'Churn_Risk', 'Predicted_LTV', 'Category']],
#             use_container_width=True,
#             hide_index=True
#         )
#     else:
#         st.success("No high-alert users currently detected in this range.")
# 
#     st.subheader("📊 Risk Landscape Chart")
#     chart = alt.Chart(filtered_df).mark_circle(size=100).encode(
#         x='Churn_Risk', y='Predicted_LTV', color='Category',
#         tooltip=['CustomerId', 'Category', 'Churn_Risk']
#     ).interactive()
#     st.altair_chart(chart, use_container_width=True)
# 
# with col_right:
#     st.subheader("⚡ Action Engine")
# 
#     if not priority_df.empty:
#         options = sorted(priority_df['CustomerId'].unique().tolist())
# 
#         if st.session_state.locked_id not in options:
#             st.session_state.locked_id = options[0]
# 
#         selected_id = st.selectbox(
#             "Select Target",
#             options=options,
#             index=options.index(st.session_state.locked_id),
#             format_func=lambda x: format_id_label(x, df),
#             key="final_v7"
#         )
#         st.session_state.locked_id = selected_id
#         user = priority_df[priority_df['CustomerId'] == selected_id].iloc[0]
# 
#         st.info(get_rationale(user))
# 
#         # Display Status
#         if user['Is_Critical']:
#             st.warning("⚠️ This user is flagged in the High Alert List.")
# 
#         sent = user['Sentiment_Score']
#         st.markdown(f"**Sentiment Score:** `{sent:.2f}`")
# 
#         if st.button("🚀 Deploy & Mark Solved", use_container_width=True):
#             st.session_state.solved_ids.add(selected_id)
#             st.success(f"ID {selected_id} resolved and removed from active alerts.")
#             st.rerun()
#     else:
#         st.success("🎉 All selected priority targets are clear!")
# 
# # --- 8. RESOLVED ARCHIVE ---
# with st.expander("✅ View Resolved Archive"):
#     if st.session_state.solved_ids:
#         solved_data = df[df['CustomerId'].isin(st.session_state.solved_ids)]
#         st.write(solved_data[['CustomerId', 'Category', 'Churn_Risk']])
#     else:
#         st.write("No issues solved yet.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import altair as alt
# from textblob import TextBlob
# 
# # --- 1. SESSION STATE (Mental Model for 2026 graduation prep) ---
# # We keep track of which issues are already "fixed" in this set
# if 'solved_ids' not in st.session_state:
#     st.session_state.solved_ids = set()
# 
# # Anchor for the selection stability to avoid "jumping"
# if 'locked_id' not in st.session_state:
#     st.session_state.locked_id = None
# 
# st.set_page_config(page_title="Blostem Sentinel: Sovereign AI", layout="wide")
# 
# # --- 2. CUSTOM CSS STYLING (The Look) ---
# # This matches the specific metric header and alert boxes in your photo
# st.markdown("""
#     <style>
#     .main { background-color: #f8fafc; }
# 
#     /* Custom Metric Header Box */
#     .metric-container {
#         display: flex; gap: 20px;
#         background: white; border: 1px solid #e2e8f0;
#         padding: 20px; border-radius: 12px;
#         box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); margin-bottom: 25px;
#     }
#     .metric-block { flex: 1; border-left: 5px solid #3b82f6; padding-left: 15px; }
#     .metric-label { font-size: 0.8em; color: #64748b; margin-bottom: 3px; }
#     .metric-value { font-size: 1.8em; font-weight: 700; color: #1e293b; }
# 
#     /* The blue info boxes (XAI Primary/Rationale) */
#     .analysis-box {
#         background: #eff6ff; border: 1px solid #bfdbfe;
#         padding: 15px; border-radius: 10px;
#         margin-bottom: 20px; color: #1e40af; font-size: 0.9em;
#     }
# 
#     /* Critical Alert tags */
#     .critical-alert {
#         background: #fee2e2; border: 2px solid #ef4444; padding: 10px;
#         border-radius: 8px; color: #b91c1c; font-weight: 800; text-align: center;
#         margin-bottom: 15px;
#     }
#     </style>
#     """, unsafe_allow_html=True)
# 
# # --- 3. LOGIC FUNCTIONS (The Brain) ---
# def format_id_label(cust_id, full_df):
#     """Marks users in the dropdown list based on status"""
#     if cust_id in st.session_state.solved_ids:
#         return f"✅ ID: {cust_id} (RESOLVED)"
# 
#     # Check if this ID is considered critical in the main data
#     user_info = full_df.loc[full_df['CustomerId'] == cust_id].iloc[0]
#     if user_info['Is_Critical']:
#         return f"🔴 [HIGH ALERT] ID: {cust_id} - Risk: {user_info['Churn_Risk']}%"
#     return f"👤 ID: {cust_id} - Risk: {user_info['Churn_Risk']}%"
# 
# # --- 4. DATA ENGINE (Ingestion) ---
# def clean_and_tag_data(df):
#     """Processes any uploaded CSV into actionable intel"""
#     # Force necessary columns for the demo
#     if 'CustomerId' not in df.columns: df['CustomerId'] = range(1000, 1000 + len(df))
#     if 'Churn_Risk' not in df.columns: df['Churn_Risk'] = np.random.randint(10, 95, len(df))
#     if 'Predicted_LTV' not in df.columns: df['Predicted_LTV'] = np.random.randint(5000, 70000, len(df))
#     if 'Feedback' not in df.columns: df['Feedback'] = "General service feedback"
# 
#     # Categorization Logic
#     def tag_issue(text):
#         t = str(text).lower()
#         if any(w in t for w in ['app', 'slow', 'crash', 'ui']): return 'Technical'
#         if any(w in t for w in ['rate', 'fee', 'charge']): return 'Financial'
#         return 'General'
# 
#     df['Category'] = df['Feedback'].apply(tag_issue)
# 
#     # Critical flags (Risk > 80% AND High LTV)
#     df['Is_Critical'] = (df['Churn_Risk'] > 80) & (df['Predicted_LTV'] > 20000)
# 
#     # Simulated explainable AI drivers (XAI)
#     df['XAI_Primary'] = np.random.choice(['Balance', 'App Usage', 'Service Fee'], len(df))
#     df['Feature_Value'] = np.random.randint(100, 5000, len(df))
# 
#     # Sentiment Analysis (Agentic move)
#     df['Sentiment_Score'] = df['Feedback'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
#     return df
# 
# # --- 5. SIDEBAR & INGESTION ---
# st.sidebar.title("📁 Data Ingestion")
# uploaded_file = st.sidebar.file_uploader("Upload CSV", type=["csv"])
# 
# if uploaded_file is not None:
#     raw_df = pd.read_csv(uploaded_file)
#     df = clean_and_tag_data(raw_df)
# else:
#     # Use dummy data if no file is uploaded
#     dummy = pd.DataFrame({'CustomerId': range(1000, 1050)})
#     df = clean_and_tag_data(dummy)
# 
# st.sidebar.divider()
# st.sidebar.title("🎛️ Dashboard Controls")
# risk_min = st.sidebar.slider("Minimum Risk Score (%)", 0, 100, 50)
# ltv_min = st.sidebar.slider("Minimum LTV Score ($)", 0, 50000, 10000)
# 
# selected_cat = st.sidebar.multiselect(
#     "Filter Category",
#     options=['Technical', 'Financial', 'General'],
#     default=['Technical', 'Financial', 'General']
# )
# 
# # --- 6. FILTERING LOGIC & COUNTS ---
# # Step A: Filter by sliders/category
# mask = (df['Churn_Risk'] >= risk_min) & \
#        (df['Predicted_LTV'] >= ltv_min) & \
#        (df['Category'].isin(selected_cat))
# filtered_df = df[mask].copy()
# 
# # Step B: Create a distinct list of the high alert unsolved users
# high_alert_df = filtered_df[
#     (filtered_df['Is_Critical'] == True) &
#     (~filtered_df['CustomerId'].isin(st.session_state.solved_ids))
# ]
# 
# # Step C: General watchlist for action (excludes solved)
# priority_df = filtered_df[~filtered_df['CustomerId'].isin(st.session_state.solved_ids)]
# 
# # --- 7. TOP METRIC HEADER (Matches Photo) ---
# st.title("🛡️ Blostem Sentinel: Sovereign AI")
# 
# # Create custom metric header with HTML/CSS
# avg_risk = filtered_df['Churn_Risk'].mean() if not filtered_df.empty else 0
# total_ltv = filtered_df['Predicted_LTV'].sum() if not filtered_df.empty else 0
# priority_count = len(priority_df)
# 
# st.markdown(f"""
#     <div class="metric-container">
#         <div class="metric-block">
#             <div class="metric-label">Avg Risk Score</div>
#             <div class="metric-value">{avg_risk:.1f}%</div>
#         </div>
#         <div class="metric-block">
#             <div class="metric-label">Total LTV at Risk</div>
#             <div class="metric-value">${total_ltv:,.0f}</div>
#         </div>
#         <div class="metric-block">
#             <div class="metric-label">Watchlist Profiles</div>
#             <div class="metric-value">{priority_count}</div>
#         </div>
#     </div>
# """, unsafe_allow_html=True)
# 
# # --- 8. MAIN UI LAYOUT ---
# col_left, col_right = st.columns([1.5, 1])
# 
# with col_left:
#     st.subheader("📊 Strategic Risk Mapping")
# 
#     if not filtered_df.empty:
#         # Altair Configuration (Scatter chart with dynamic size/labels)
#         chart = alt.Chart(filtered_df).mark_circle(size=120, opacity=0.8).encode(
#             x=alt.X('Churn_Risk', title='Risk Score (%)', scale=alt.Scale(domain=[0, 100])),
#             y=alt.Y('Predicted_LTV', title='Predicted LTV ($)', axis=alt.Axis(format='$,.0f')),
#             color='Category',
#             tooltip=['CustomerId', 'Category', 'Churn_Risk', 'Predicted_LTV']
#         ).interactive()
#         st.altair_chart(chart, use_container_width=True)
#     else:
#         st.info("Adjust sliders to view customer landscape.")
# 
#     # High Alert List requested by the user
#     with st.expander("🚨 Critical Exposure (High Alert Users)", expanded=True):
#         if not high_alert_df.empty:
#             st.dataframe(
#                 high_alert_df[['CustomerId', 'Churn_Risk', 'Predicted_LTV', 'Category', 'XAI_Primary']],
#                 use_container_width=True,
#                 hide_index=True
#             )
#         else:
#             st.success("Watchlist is clear of unresolved high-alert users.")
# 
# with col_right:
#     st.subheader("⚡ Action Engine")
# 
#     if not priority_df.empty:
#         # Create a stable sorted list of options
#         options = sorted(priority_df['CustomerId'].unique().tolist())
# 
#         # Stability Lock
#         if st.session_state.locked_id not in options:
#             st.session_state.locked_id = options[0]
# 
#         selected_id = st.selectbox(
#             "Select Target Profile",
#             options=options,
#             index=options.index(st.session_state.locked_id),
#             format_func=lambda x: format_id_label(x, df), # The icon logic
#             key="final_selectbox_v7"
#         )
#         st.session_state.locked_id = selected_id
#         user = priority_df[priority_df['CustomerId'] == selected_id].iloc[0]
# 
#         # XAI Analysis Primary (The top blue info box)
#         st.markdown("### 🧠 XAI Primary Driver")
#         st.markdown(f"""<div class="analysis-box">
#             <b>{user['XAI_Primary']}:</b> {user['Feature_Value']:,.0f} weighted contribution to risk score.
#             </div>""", unsafe_allow_html=True)
# 
#         # Agentic Rationale Box
#         f = user['XAI_Primary']
#         rationale_text = f"Anomalous {f} patterns detected. Suggesting {user['Category']} stabilization protocol to secure account."
#         if user['Is_Critical']:
#             st.markdown('<div class="critical-alert">⚠️ Flagged in Critical List</div>', unsafe_allow_html=True)
#             rationale_text = f"🚨 Priority Deployment required. Sudden {f} variance affects {user['Category']} stability."
# 
#         st.info(rationale_text)
# 
#         # Deploy and Solve Button (Added 'Remove from list' feature)
#         if st.button("🚀 Deploy Protocol & Solve Issue", use_container_width=True):
#             st.session_state.solved_ids.add(selected_id)
#             st.rerun() # Refresh so they immediately vanish from the priority list
#     else:
#         st.success("All selected priority profiles have been resolved!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import altair as alt
# from datetime import datetime
# from textblob import TextBlob
# 
# # --- 1. INITIALIZATION & SESSION STATE ---
# if 'solved_ids' not in st.session_state:
#     st.session_state.solved_ids = set()
# if 'audit_log' not in st.session_state:
#     st.session_state.audit_log = []
# if 'locked_id' not in st.session_state:
#     st.session_state.locked_id = None
# 
# st.set_page_config(page_title="Blostem Sentinel: Sovereign AI", layout="wide")
# 
# # --- 2. HIGH-END THEMING (Typography & Glassmorphism) ---
# st.markdown("""
#     <style>
#     @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=JetBrains+Mono&display=swap');
# 
#     html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
#     .mono { font-family: 'JetBrains Mono', monospace; font-weight: 500; }
# 
#     /* Metric Card Styling */
#     .metric-card {
#         background: white; border: 1px solid #e2e8f0; padding: 20px;
#         border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
#     }
#     .metric-value { font-family: 'JetBrains Mono'; font-size: 2rem; font-weight: 700; color: #0f172a; }
# 
#     /* Audit Log Styling */
#     .audit-entry { font-family: 'JetBrains Mono'; font-size: 0.8rem; padding: 4px 0; border-bottom: 1px solid #f1f5f9; }
# 
#     /* Sidebar Compactness */
#     section[data-testid="stSidebar"] { width: 300px !important; }
#     </style>
#     """, unsafe_allow_html=True)
# 
# # --- 3. CORE LOGIC & DATA GENERATION ---
# @st.cache_data
# def load_data(rows=50):
#     df = pd.DataFrame({
#         'CustomerId': range(1000, 1000 + rows),
#         'Churn_Risk': np.random.randint(10, 98, rows),
#         'Predicted_LTV': np.random.randint(5000, 150000, rows),
#         'Confidence': np.random.uniform(85, 99.9, rows),
#         'Feedback': np.random.choice(['High fees', 'Slow app', 'Great service', 'Transfer failed'], rows),
#         'Tx_Frequency': np.random.randint(1, 100, rows),
#         'Market_Sentiment': np.random.uniform(-1, 1, rows)
#     })
# 
#     def tag_category(row):
#         t = row['Feedback'].lower()
#         if any(w in t for w in ['fee', 'rate', 'transfer']): return 'Financial'
#         if any(w in t for w in ['app', 'slow', 'failed']): return 'Technical'
#         return 'General Service'
# 
#     df['Category'] = df.apply(tag_category, axis=1)
#     df['Is_Critical'] = (df['Churn_Risk'] > 80) & (df['Predicted_LTV'] > 100000)
#     return df
# 
# def add_audit(action):
#     now = datetime.now().strftime("%H:%M:%S")
#     st.session_state.audit_log.insert(0, f"[{now}] - {action}")
# 
# # --- 4. DATA INGESTION & FILTERING ---
# with st.sidebar:
#     st.title("📁 Ingestion")
#     uploaded = st.file_uploader("Upload CSV", type="csv", label_visibility="collapsed")
#     df = pd.read_csv(uploaded) if uploaded else load_data()
# 
#     st.divider()
#     st.subheader("🎛️ Parameters")
#     risk_range = st.slider("Min Risk Score", 0, 100, 40)
#     ltv_range = st.slider("Min LTV ($)", 0, 150000, 20000)
#     scale_type = st.radio("Chart Scale", ["Linear", "Logarithmic"], horizontal=True)
# 
# # Filtering logic
# mask = (df['Churn_Risk'] >= risk_range) & (df['Predicted_LTV'] >= ltv_range)
# filtered_df = df[mask].copy()
# priority_df = filtered_df[~filtered_df['CustomerId'].isin(st.session_state.solved_ids)]
# 
# # --- 5. TOP HEADER METRICS ---
# st.title("🛡️ Blostem Sentinel: Sovereign AI")
# m1, m2, m3, m4 = st.columns(4)
# with m1: st.markdown(f'<div class="metric-card"><p>Risk Segment</p><p class="metric-value">{len(priority_df)}</p></div>', unsafe_allow_html=True)
# with m2: st.markdown(f'<div class="metric-card"><p>Total Exposure</p><p class="metric-value">${priority_df["Predicted_LTV"].sum():,}</p></div>', unsafe_allow_html=True)
# with m3: st.markdown(f'<div class="metric-card"><p>Sovereign Status</p><p class="metric-value" style="color:#10b981;">SECURE</p></div>', unsafe_allow_html=True)
# with m4: st.markdown(f'<div class="metric-card"><p>Regulatory</p><p class="metric-value" style="font-size:1.2rem;">RBI COMPLIANT</p></div>', unsafe_allow_html=True)
# 
# st.divider()
# 
# # --- 6. MAIN INTERFACE ---
# col_left, col_right = st.columns([1.8, 1])
# 
# with col_left:
#     st.subheader("📊 Strategic Risk Mapping")
# 
#     # Quadrant Chart with Faint Backgrounds
#     scale_choice = 'log' if scale_type == "Logarithmic" else 'linear'
# 
#     scatter = alt.Chart(filtered_df).mark_circle(size=120, stroke="white", strokeWidth=1).encode(
#         x=alt.X('Churn_Risk', title='Risk Score (%)', scale=alt.Scale(domain=[0, 100])),
#         y=alt.Y('Predicted_LTV', title='Predicted LTV ($)', scale=alt.Scale(type=scale_choice)),
#         color=alt.Color('Category', scale=alt.Scale(domain=['Financial', 'Technical', 'General Service'], range=['#3b82f6', '#ef4444', '#64748b'])),
#         tooltip=[
#             alt.Tooltip('CustomerId', title='ID'),
#             alt.Tooltip('Churn_Risk', title='Risk (%)'),
#             alt.Tooltip('Predicted_LTV', title='LTV ($)', format="$,.0f"),
#             alt.Tooltip('Category', title='Category')
#         ]
#     )
# 
#     # Adding Quadrant Lines
#     rule_x = alt.Chart(pd.DataFrame({'x': [50]})).mark_rule(strokeDash=[4,4], color='#cbd5e1').encode(x='x')
#     rule_y = alt.Chart(pd.DataFrame({'y': [75000]})).mark_rule(strokeDash=[4,4], color='#cbd5e1').encode(y='y')
# 
#     st.altair_chart(scatter + rule_x + rule_y, use_container_width=True)
# 
#     # System Activity Feed (Audit Log)
#     st.subheader("📜 System Activity Audit")
#     log_container = st.container(height=150)
#     for entry in st.session_state.audit_log[:10]:
#         log_container.markdown(f'<div class="audit-entry">{entry}</div>', unsafe_allow_html=True)
# 
# with col_right:
#     st.subheader("⚡ Action Engine")
# 
#     if not priority_df.empty:
#         ids = sorted(priority_df['CustomerId'].tolist())
#         if st.session_state.locked_id not in ids: st.session_state.locked_id = ids[0]
# 
#         selected_id = st.selectbox("Select Target Profile", ids, index=ids.index(st.session_state.locked_id))
#         st.session_state.locked_id = selected_id
#         user = priority_df[priority_df['CustomerId'] == selected_id].iloc[0]
# 
#         # XAI AI BRAIN UPGRADE
#         st.markdown(f"### 🧠 AI Rationale (ID-{selected_id})")
#         st.progress(user['Confidence']/100, text=f"Model Confidence: {user['Confidence']:.1f}%")
# 
#         # Horizontal Bar Chart for Feature Importance
#         feat_data = pd.DataFrame({
#             'Factor': ['Tx Frequency', 'LTV Drop', 'Market Sentiment', 'Service Usage'],
#             'Weight': [user['Tx_Frequency'], np.random.randint(20, 80), abs(user['Market_Sentiment']*100), 45]
#         })
#         feat_chart = alt.Chart(feat_data).mark_bar(cornerRadiusEnd=4, color="#3b82f6").encode(
#             x=alt.X('Weight', title=None, axis=None),
#             y=alt.Y('Factor', sort='-x', title=None)
#         ).properties(height=120)
#         st.altair_chart(feat_chart, use_container_width=True)
# 
#         st.info(f"**Observation:** Anomalous {user['Category']} behavior detected. Liquidity variance exceeds safety threshold.")
# 
#         # FINTECH MOAT: Regulatory Buttons
#         c1, c2 = st.columns(2)
#         with c1:
#             if st.button("🚀 Deploy Protocol", use_container_width=True):
#                 st.session_state.solved_ids.add(selected_id)
#                 add_audit(f"ID-{selected_id} resolved via stabilization protocol.")
#                 st.rerun()
#         with c2:
#             if st.button("🛑 Regulatory Halt", type="secondary", use_container_width=True):
#                 add_audit(f"CRITICAL: Regulatory Halt initiated for ID-{selected_id}.")
#                 st.error("Account Frozen for Compliance")
# 
#     else:
#         st.success("🎉 Sovereign Watchlist Clear")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import altair as alt
# from datetime import datetime
# from textblob import TextBlob
# 
# # --- 1. INITIALIZATION & SESSION STATE ---
# if 'solved_ids' not in st.session_state:
#     st.session_state.solved_ids = set()
# if 'audit_log' not in st.session_state:
#     st.session_state.audit_log = []
# if 'locked_id' not in st.session_state:
#     st.session_state.locked_id = None
# 
# st.set_page_config(page_title="Blostem Sentinel: Sovereign AI", layout="wide")
# 
# # --- 2. HIGH-END THEMING (Typography & Glassmorphism) ---
# st.markdown("""
#     <style>
#     @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=JetBrains+Mono&display=swap');
# 
#     html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
#     .mono { font-family: 'JetBrains Mono', monospace; font-weight: 500; }
# 
#     /* Metric Card Styling */
#     .metric-card {
#         background: white; border: 1px solid #e2e8f0; padding: 20px;
#         border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
#     }
#     .metric-value { font-family: 'JetBrains Mono'; font-size: 2rem; font-weight: 700; color: #0f172a; }
# 
#     /* Audit Log Styling */
#     .audit-entry { font-family: 'JetBrains Mono'; font-size: 0.8rem; padding: 4px 0; border-bottom: 1px solid #f1f5f9; }
# 
#     /* Sidebar Compactness */
#     section[data-testid="stSidebar"] { width: 300px !important; }
#     </style>
#     """, unsafe_allow_html=True)
# 
# # --- 3. CORE LOGIC & DATA GENERATION ---
# @st.cache_data
# def load_data(rows=50):
#     df = pd.DataFrame({
#         'CustomerId': range(1000, 1000 + rows),
#         'Churn_Risk': np.random.randint(10, 98, rows),
#         'Predicted_LTV': np.random.randint(5000, 150000, rows),
#         'Confidence': np.random.uniform(85, 99.9, rows),
#         'Feedback': np.random.choice(['High fees', 'Slow app', 'Great service', 'Transfer failed'], rows),
#         'Tx_Frequency': np.random.randint(1, 100, rows),
#         'Market_Sentiment': np.random.uniform(-1, 1, rows)
#     })
# 
#     def tag_category(row):
#         t = row['Feedback'].lower()
#         if any(w in t for w in ['fee', 'rate', 'transfer']): return 'Financial'
#         if any(w in t for w in ['app', 'slow', 'failed']): return 'Technical'
#         return 'General Service'
# 
#     df['Category'] = df.apply(tag_category, axis=1)
#     df['Is_Critical'] = (df['Churn_Risk'] > 80) & (df['Predicted_LTV'] > 100000)
#     return df
# 
# def add_audit(action):
#     now = datetime.now().strftime("%H:%M:%S")
#     st.session_state.audit_log.insert(0, f"[{now}] - {action}")
# 
# # Formatted list labels
# def format_id_display(cust_id, full_df):
#     if cust_id in st.session_state.solved_ids:
#         return f"✅ ID: {cust_id} (RESOLVED)"
#     user_row = full_df[full_df['CustomerId'] == cust_id].iloc[0]
#     if user_row['Is_Critical']:
#         return f"🔴 ID: {cust_id} (HIGH ALERT)"
#     return f"👤 ID: {cust_id}"
# 
# # --- 4. DATA INGESTION & FILTERING ---
# with st.sidebar:
#     st.title("📁 Ingestion")
#     uploaded = st.file_uploader("Upload CSV", type="csv", label_visibility="collapsed")
#     df = pd.read_csv(uploaded) if uploaded else load_data()
# 
#     st.divider()
#     st.subheader("🎛️ Parameters")
#     risk_range = st.slider("Min Risk Score", 0, 100, 40)
#     ltv_range = st.slider("Min LTV ($)", 0, 150000, 20000)
#     scale_type = st.radio("Chart Scale", ["Linear", "Logarithmic"], horizontal=True)
# 
#     # NEW: Category Filter
#     selected_categories = st.multiselect(
#         "Filter Category",
#         options=['Financial', 'Technical', 'General Service'],
#         default=['Financial', 'Technical', 'General Service']
#     )
# 
# # Filtering logic
# mask = (df['Churn_Risk'] >= risk_range) & \
#        (df['Predicted_LTV'] >= ltv_range) & \
#        (df['Category'].isin(selected_categories))
# filtered_df = df[mask].copy()
# 
# # All available IDs for the selector
# available_ids = filtered_df['CustomerId'].unique().tolist()
# # Only unsolved IDs for priority logic
# priority_df = filtered_df[~filtered_df['CustomerId'].isin(st.session_state.solved_ids)]
# 
# # --- 5. TOP HEADER METRICS ---
# st.title("🛡️ Blostem Sentinel: Sovereign AI")
# m1, m2, m3, m4 = st.columns(4)
# with m1: st.markdown(f'<div class="metric-card"><p>Risk Segment</p><p class="metric-value">{len(priority_df)}</p></div>', unsafe_allow_html=True)
# with m2: st.markdown(f'<div class="metric-card"><p>Total Exposure</p><p class="metric-value">${priority_df["Predicted_LTV"].sum():,}</p></div>', unsafe_allow_html=True)
# with m3: st.markdown(f'<div class="metric-card"><p>Sovereign Status</p><p class="metric-value" style="color:#10b981;">SECURE</p></div>', unsafe_allow_html=True)
# with m4: st.markdown(f'<div class="metric-card"><p>Regulatory</p><p class="metric-value" style="font-size:1.2rem;">RBI COMPLIANT</p></div>', unsafe_allow_html=True)
# 
# st.divider()
# 
# # --- 6. MAIN INTERFACE ---
# col_left, col_right = st.columns([1.8, 1])
# 
# with col_left:
#     st.subheader("📊 Strategic Risk Mapping")
# 
#     scale_choice = 'log' if scale_type == "Logarithmic" else 'linear'
# 
#     scatter = alt.Chart(filtered_df).mark_circle(size=120, stroke="white", strokeWidth=1).encode(
#         x=alt.X('Churn_Risk', title='Risk Score (%)', scale=alt.Scale(domain=[0, 100])),
#         y=alt.Y('Predicted_LTV', title='Predicted LTV ($)', scale=alt.Scale(type=scale_choice)),
#         color=alt.Color('Category', scale=alt.Scale(domain=['Financial', 'Technical', 'General Service'], range=['#3b82f6', '#ef4444', '#64748b'])),
#         tooltip=[
#             alt.Tooltip('CustomerId', title='ID'),
#             alt.Tooltip('Churn_Risk', title='Risk (%)'),
#             alt.Tooltip('Predicted_LTV', title='LTV ($)', format="$,.0f"),
#             alt.Tooltip('Category', title='Category')
#         ]
#     )
# 
#     rule_x = alt.Chart(pd.DataFrame({'x': [50]})).mark_rule(strokeDash=[4,4], color='#cbd5e1').encode(x='x')
#     rule_y = alt.Chart(pd.DataFrame({'y': [75000]})).mark_rule(strokeDash=[4,4], color='#cbd5e1').encode(y='y')
# 
#     st.altair_chart(scatter + rule_x + rule_y, use_container_width=True)
# 
#     st.subheader("📜 System Activity Audit")
#     log_container = st.container(height=150)
#     for entry in st.session_state.audit_log[:10]:
#         log_container.markdown(f'<div class="audit-entry">{entry}</div>', unsafe_allow_html=True)
# 
# with col_right:
#     st.subheader("⚡ Action Engine")
# 
#     if available_ids:
#         ids = sorted(available_ids)
#         if st.session_state.locked_id not in ids: st.session_state.locked_id = ids[0]
# 
#         # Updated Selectbox with Format Function to show icons
#         selected_id = st.selectbox(
#             "Select Target Profile",
#             ids,
#             index=ids.index(st.session_state.locked_id),
#             format_func=lambda x: format_id_display(x, filtered_df)
#         )
#         st.session_state.locked_id = selected_id
#         user = filtered_df[filtered_df['CustomerId'] == selected_id].iloc[0]
# 
#         st.markdown(f"### 🧠 AI Rationale (ID-{selected_id})")
#         st.progress(user['Confidence']/100, text=f"Model Confidence: {user['Confidence']:.1f}%")
# 
#         feat_data = pd.DataFrame({
#             'Factor': ['Tx Frequency', 'LTV Drop', 'Market Sentiment', 'Service Usage'],
#             'Weight': [user['Tx_Frequency'], np.random.randint(20, 80), abs(user['Market_Sentiment']*100), 45]
#         })
#         feat_chart = alt.Chart(feat_data).mark_bar(cornerRadiusEnd=4, color="#3b82f6").encode(
#             x=alt.X('Weight', title=None, axis=None),
#             y=alt.Y('Factor', sort='-x', title=None)
#         ).properties(height=120)
#         st.altair_chart(feat_chart, use_container_width=True)
# 
#         # Handling UI if resolved
#         if selected_id in st.session_state.solved_ids:
#             st.success("Protocol Active: This account is currently secured.")
#         else:
#             st.info(f"**Observation:** Anomalous {user['Category']} behavior detected. Liquidity variance exceeds safety threshold.")
# 
#             c1, c2 = st.columns(2)
#             with c1:
#                 if st.button("🚀 Deploy Protocol", use_container_width=True):
#                     st.session_state.solved_ids.add(selected_id)
#                     add_audit(f"ID-{selected_id} resolved via stabilization protocol.")
#                     st.rerun()
#             with c2:
#                 if st.button("🛑 Regulatory Halt", type="secondary", use_container_width=True):
#                     add_audit(f"CRITICAL: Regulatory Halt initiated for ID-{selected_id}.")
#                     st.error("Account Frozen for Compliance")
#     else:
#         st.success("🎉 Sovereign Watchlist Clear")

# 1. Kill existing tunnels
!pkill ngrok

# 2. Restart Streamlit in the background
import os
os.system("nohup streamlit run app.py &")

# 3. Create a fresh tunnel
from pyngrok import ngrok
# Replace 'YOUR_AUTHTOKEN' if you haven't set it yet
# ngrok.set_auth_token("YOUR_AUTHTOKEN")

try:
    public_url = ngrok.connect(8501)
    print(f"Click here for your Dashboard: {public_url}")
except Exception as e:
    print(f"Error: {e}. Try restarting the Colab runtime.")